baseURL = '/'
languageCode = 'en-us'
title = 'All Beings'
theme = 'hugo-tufte'
canonifyURLs = true

[params]
  KaTeXCDN = "https://cdn.jsdelivr.net/npm"
  KaTeXVersion = "0.16.7"

[permalinks]
  posts = "/:title/"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
