baseURL = 'https://nsbarr.github.io/self-therapy/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'hugo-tufte'
custom_css = ["css/custom.css"]
canonifyURLs = true
[permalinks]
  posts = "/:title/"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true