baseURL = '/'
languageCode = 'en-us'
title = ''
theme = 'hugo-tufte'
custom_css = ["css/custom.css"]
canonifyURLs = true

[params]
  KaTeXCDN = "https://cdn.jsdelivr.net/npm"
  KaTeXVersion = "0.16.7"

[permalinks]
  posts = "/:title/"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[menu]
  [[menu.main]]
    name = "Devotional Watching"
    url = "/devotional-watching/"
    weight = 5